# action.yml
name: 'PDFlatex'
description: 'Runs pdflatex on tex files'
inputs:
  texFile:  # id of input
    description: 'name of the tex file'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.texFile }}
